#! /bin/bash

echo "Beginning to test Trellonos"

# Runtime configuration
source ~/.trellorc

# Discover unit tests and run them
cd $SRC_DIR
python -m unittest discover

echo "Finished testing Trellonos"
