#! /bin/bash

ROOT_DIR=~/Trellonos
SRC_DIR=$ROOT_DIR/trellonos

echo "Beginning to test Trellonos"

# Runtime configuration
cd $ROOT_DIR
source ./.trellorc

# Discover unit tests and run them
cd $SRC_DIR
python -m unittest discover

echo "Finished testing Trellonos"
